### ISSUE TITLE
Invalid selector raises Error but null won't

### ISSUE THREAD

**Issue by bartaelterman** [d3/d3-selection#100]
Mike,

Is there a reason why at [this line](https://github.com/d3/d3-selection/blob/master/src/selector.js#L4) you catch `null` and return `none`? I can throw in other invalid selectors (such as an empty string) but they will cause the next line to throw an error.

Would it be an option to test whether the selector is a valid selector instead of checking whether it is null or not?

**Comment by mbostock** [comment]
If you click [the blame link](https://github.com/d3/d3-selection/blame/master/src/selector.js#L4) for that file, it will show you [the commit](https://github.com/d3/d3-selection/commit/4a7f3ba69900809692dcb84160b2a0112df64096) that last edited that line, which has the description:

> **More sensible select\[All\](null).**
>
> Previously it was being coerced to a string, and so it could (in very unlikely
scenarios) select \<null\> or \<undefined\> elements; now it only selects nothing.
> 
> Related #79.

To summarize: *null* was not an invalid selector. It was coerced to the string “null” which would match any elements with the name “null” (and similarly *undefined* was equivalent to “undefined”). This is similar to how in JavaScript `foo["null"] = 42` and `foo[null] = 42` are equivalent. Despite being valid, this coercion was confusing since it was used by some to intentionally select nothing before a data-join, so it was changed in the above commit to always return the empty selection.

**Comment by bartaelterman** [comment]
Makes sense. Thanks.
