### ISSUE TITLE
selection.style trigger a error in IE11

### ISSUE THREAD

**Issue by yandongCoder** [d3/d3-selection#107]
It will trigger an error if you get or set style to a foreignObject element in IE11, because browser not provide this property to foreignObject element. it's meaning this.style is undefined, is this bug need fixed?

**Comment by mbostock** [comment]
This sounds like the expected behavior: if an element (such as foreignObject in IE) has no style object, you can’t use *selection*.style on it. D3 is not a compatibility layer. You probably want to apply the style to the child of the foreignObject instead.

Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
