### ISSUE TITLE
role of key function in selection.data

### ISSUE THREAD

**Issue by NPashaP** [d3/d3-selection#108]
In the following code, between the two selections, the data has changed but the key set hasn't changed. The second selection should have returned empty selection for enter but it isn't. It makes me wonder as to how is the key function used, I was thinking that it is used to check equivalence of data elements. 

```javascript
    selectAll("p")
    .data([{k:'A'}], function(d){ return d.k;})
    .enter()
    .append("p")
    .text(function(d){ return d.k});

    .selectAll("p")
    .data([{s:'A'}], function(d){ return d.s;})
    .enter()
    .append("p")
    .text(function(d){ return d.s});
```

Is this a defect or that is how it should be?

**Comment by mbostock** [comment]
Keys are not saved, so it doesn’t reuse the key you computed from the previous data-join: it computes a new key from the selected element’s datum using the key function you specified. So in the second case, the selected element has a key of `"undefined"` (since `({k:'A'}).s` is undefined), while the new datum has a key of `"A"`.

If you have further questions, please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
