### ISSUE TITLE
add Passive event listener arguments to .on()

### ISSUE THREAD

**Issue by mark3448** [d3/d3-selection#113]
talking about this:
https://dom.spec.whatwg.org/#dictdef-eventlisteneroptions

for more information: 
https://medium.com/@devlucky/about-passive-event-listeners-224ff620e68c#.1awhbyd87

could be good to add:
  on(type:string, listener?:$$.ValueFunction<void>, capture?:boolean, options?):this;

and then you could do .on('click',()=>,{passive: true});

**Comment by mbostock** [comment]
This already works because *selection*.on just passes through the optional third *capture* argument without any consideration as to what it means or what type it has. For example:

```js
d3.select("body").on("click", () => console.log("click"), {once: true})
```

So, the simplest thing to do would be to rename *capture* in the documentation (and internal parts of the code) to *options*, and then close this issue.

**Comment by xiaoshidetaikuai** [comment]
excuse me,How can I use passive for zoom?  I see code is
```
 selection
        .property("__zoom", defaultTransform)
        .on("wheel.zoom", wheeled)
        .on("mousedown.zoom", mousedowned)
        .on("dblclick.zoom", dblclicked)
      .filter(touchable)
        .on("touchstart.zoom", touchstarted)
        .on("touchmove.zoom", touchmoved)
        .on("touchend.zoom touchcancel.zoom", touchended)
        .style("touch-action", "none")
        .style("-webkit-tap-highlight-color", "rgba(0,0,0,0)");
```

**Comment by mbostock** [comment]
@xiaoshidetaikuai See https://github.com/d3/d3-drag/issues/35#issuecomment-314798648
