### ISSUE TITLE
exit() lost after merge()

### ISSUE THREAD

**Issue by curran** [d3/d3-selection#115]
Forgive me if I'm misunderstanding something here, but I'm surprised that the the behavior of `.exit()` is not preserved after a `.merge()`.

As an example, the following works as expected ([bl.ock](https://bl.ocks.org/curran/d406e6f18ceb49f47c9376605f85be74)):

```js
var circles = svg
  .selectAll("circle").data(data);

circles
  .enter().append("circle")
    .attr("cy", 250)
    .attr("r", 100)
  .merge(circles)
    .attr("cx", function (d){ return d; });

circles.exit().remove();
```

But the following does not remove any nodes ([bl.ock](https://bl.ocks.org/curran/fb34f73f8f990a212caf9ef6cf2aadd1)):

```js
var circles = svg
  .selectAll("circle").data(data);

circles
  .enter().append("circle")
    .attr("cy", 250)
    .attr("r", 100)
  .merge(circles)
    .attr("cx", function (d){ return d; })
  .exit().remove();
```

The exit() behavior is also missing in the case that the merge order is inverted ([bl.ock](http://bl.ocks.org/curran/9218530ea7ab1bce03fa46b68558a15f)):

```js
var circles = svg
  .selectAll("circle").data(data);

circles
  .merge(circles.enter().append("circle")
    .attr("cy", 250)
    .attr("r", 100)
  )
    .attr("cx", function (d){ return d; })
  .exit().remove();
```

Is there any statement in the README that I missed that indicates that this is the expected behavior?

**Comment by swinc** [comment]
It's a bit subtle but `.merge` just returns a d3 `selection` (without `enter` and `exit` properties) where as `.data` returns an `enter selection` with those properties.

I think it's technically stated that way in the docs (merge "returns a new selection", data returns a new selection that "also defines the enter and exit selections") but I agree it could be clearer.

So I believe this is expected behavior.

**Comment by mbostock** [comment]
Yes, this is the expected behavior; *selection*.merge returns a new selection, dropping information about the prior data join, and thus *selection*.enter and *selection*.exit return the empty selection on the merged selection. The only time that *selection*.enter and *selection*.exit return a non-empty selection is if *selection* was returned from *selection*.data.

**Comment by curran** [comment]
Ok, got it. Thanks for clarifying.
