### ISSUE TITLE
enter.call returns EnterNodes

### ISSUE THREAD

**Issue by zakandrewking** [d3/d3-selection#116]
I am porting an app from D3 v3 to v4, and I came across the following issue. I am not sure if this is the intended behavior, but it did cause me some confusion.

I use the `call` method on enter selections regularly, like this:

```js
const d_sel = sel.selectAll('.text').data(data)
const e_sel = d_sel.enter().call(e => e.append('div').attr('class', 'text'))
```

This is great, because I can separate out the logic for adding, removing, and updating into functions. However, the `e_sel` variable above contains EnterNodes, even after I append DOM elements. Therefore, this example has different behavior:

```js
const d_sel = sel.selectAll('.text').data(data)
const e_sel = d_sel.enter().append('div').call(e => e.attr('class', 'text'))
```

Now, `e_sel` contains real nodes instead of EnterNodes, and I can inspect them the way I expect, e.g. pull out my class attribute:

```js
e_sel.nodes().map(n => d3.select(n).attr('class'))
```

That line only works with the second example. Thanks in advance for taking a look!

Full working example:

https://jsfiddle.net/mvLf579a/

**Comment by mbostock** [comment]
This is the expected behavior because *selection*.call returns the current *selection*, not the return value of the function you call. And furthermore, selections are immutable, so calling *selection*.append on the *enter* selection returns a new selection, but does not affect the contents of the *enter* selection.

See #102 for changing the behavior of *selection*.call, but note that this requires a major version change, and even then it might be better to use a different name to make migration easier.

You can achieve similar functionality without *selection*.call by just calling the function yourself:

```js
const d_sel = sel.selectAll('.text').data(data)
const e_sel = (e => e.append('div').attr('class', 'text'))(d_sel.enter())
```
