### ISSUE TITLE
merge() after filter() works inconsistently

### ISSUE THREAD

**Issue by Paulskit** [d3/d3-selection#136]
Here is the demo:
https://bl.ocks.org/Paulskit/36473b56d6e7df12ef2d611b3292efa4

I'm not sure if that's an issue or a feature, but it's definitely confusing. You expect A + B = C and B + A  = C. In our case, if filter() used the order matters.

**Comment by mbostock** [comment]
This is the expected behavior. Please read the documentation for [*selection*.merge](https://github.com/d3/d3-selection/blob/master/README.md#selection_merge) and [*selection*.filter](https://github.com/d3/d3-selection/blob/master/README.md#selection_filter). If you want to filter while preserving the indexes, you must use [*selection*.select](https://github.com/d3/d3-selection/blob/master/README.md#selection_select) instead of *selection*.filter.
