### ISSUE TITLE
Add: selection.classed("foo", toggle);

### ISSUE THREAD

**Issue by DougManuel** [d3/d3-selection#137]
Suggestion to add feature or give example in documentation about how to code using existing currently available true/false values. 

Rationale for:
- Common use case? (included in JQuery as `toggleClass`).
- A bit challenging to code using currently allowed true/false values? especially for `.selectAll()`
- Straightforward  and clear addition?

Argument against:
- Only partially consistent with current approach. _value_ accepts a function (toggle is really a function), but returns truthy.

See: [https://jaketrent.com/post/d3-class-operations/](https://jaketrent.com/post/d3-class-operations/)

**Comment by mbostock** [comment]
No plans to do this.

Partly this is because toggling is not especially idiomatic for D3, as the resulting DOM state is not data-driven but instead driven by the previous state of the DOM. So, a more idiomatic approach would be to toggle some data state, and then derive the new class based on the data. For example:

```js
selection.classed("active", d => d.active = !d.active);
```

If you do want to toggle the class of a selection of elements, rather than using *selection*.classed to read the current state of each element, I would probably use the DOM API directly:

```js
selection.classed("active", function() { return !this.classList.contains("active"); });
```

Or, using an arrow function:

```js
selection.classed("active", (d, i, nodes) => !nodes[i].classList.contains("column"));
```

If you find yourself doing this often, you could write a plugin that extends d3.selection.prototype to add a method. (See also [d3-jetpack](https://github.com/gka/d3-jetpack).)
