### ISSUE TITLE
insert is not working like in d3@3.x

### ISSUE THREAD

**Issue by NonPolynomial** [d3/d3-selection#144]
I wanted to create a definition list like this:
```html
<dl>
  <dt>foo</dt>
  <dd>bar</dd>
  <dt>baz</dt>
  <dd>quaax</dd>
  <dt>lorem</dt>
  <dd>ipsum</dd>
</dl>
```
from this data: 
```json
{
  "foo": "bar",
  "baz": "quaax",
  "lorem": "ipsum"
}
```

I found [this](https://stackoverflow.com/questions/21485981/appending-multiple-non-nested-elements-for-each-data-member-with-d3-js) answer on stack overflow an saw, that there is a `insert` function which does exactly what I need without an unneccassary sort.

I use d3 in version 4 and there that `insert` function just *appending* the element.
[I tried that code, working in version 3, but not in version 4](https://stackoverflow.com/a/29578395/7484121)

**Comment by mbostock** [comment]
Copied from the [1.0.0 release notes](https://github.com/d3/d3-selection/releases/v1.0.0):

In 3.x, [_selection_.append](https://github.com/d3/d3-selection#selection_append) would always append the new element as the last child of its parent. A little-known trick was to use [_selection_.insert](https://github.com/d3/d3-selection#selection_insert) without specifying a _before_ selector when entering nodes, causing the entering nodes to be inserted before the following element in the update selection. In 4.0, this is now the default behavior of _selection_.append; if you do not specify a _before_ selector to _selection_.insert, the inserted element is appended as the last child. This change makes the general update pattern preserve the relative order of elements and data. For example, given the following DOM:

``` html
<div>a</div>
<div>b</div>
<div>f</div>
```

And the following code:

``` js
var div = d3.select("body").selectAll("div")
  .data(["a", "b", "c", "d", "e", "f"], function(d) { return d || this.textContent; });

div.enter().append("div")
    .text(function(d) { return d; });
```

The resulting DOM will be:

``` html
<div>a</div>
<div>b</div>
<div>c</div>
<div>d</div>
<div>e</div>
<div>f</div>
```

Thus, the entering _c_, _d_ and _e_ are inserted before _f_, since _f_ is the following element in the update selection. Although this behavior is sufficient to preserve order if the new data’s order is stable, if the data changes order, you must still use [_selection_.order](https://github.com/d3/d3-selection#selection_order) to reorder elements.

**Comment by mbostock** [comment]
If you have further questions, please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by NonPolynomial** [comment]
@mbostock thanks for your answer.
I already looked for a solution on stackoverflow and found the answer that insetr would append a sibling and was just wondering that it didn't work anymore in version 4.
for more details see [this collection on codepen](https://codepen.io/collection/DjyzdB/).
I wrote 2 examples: one with version 3 and one with verison 4.

So the only way in version 4 to display connected data entries is to sort them after appending, right?

**Comment by mbostock** [comment]
You are trying to append to the *enter* selection twice, which is not a good idea. The idea of the data-join is that there is a one-to-one correspondence between your data and your DOM elements. In your case you want a one-to-two correspondence, with each datum corresponding to both a DT and a DD element. The way to fix that is to create a [wrapper DIV containing the DT and DD](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl#Wrapping_name-value_groups_in_<div>_elements) for each datum.

```js
var div = d3.select("#list")
  .selectAll("div")
  .data([
    {key: "foo", value: "bar"},
    {key: "baz", value: "quaax"},
    {key: "lorem", value: "ipsum"}
  ])
  .enter().append("div");

div.append("dt")
    .text(function(d) { return d.key; });

div.append("dd")
    .text(function(d) { return d.value; });
```

Live example: https://bl.ocks.org/mbostock/492d99ad44b663a92a690513f873c82e

If you really want to avoid the wrapper DIV, then another way to do this would be to represent your data as six elements rather than three, and pass a function to *selection*.append to create the right type of DOM element for each key and value:

```js
d3.select("#list")
  .selectAll("dt,dd")
  .data([
    {type: "dt", value: "foo"},
    {type: "dd", value: "bar"},
    {type: "dt", value: "baz"},
    {type: "dd", value: "quaax"},
    {type: "dt", value: "lorem"},
    {type: "dd", value: "ipsum"}
  ])
  .enter().append(function(d) { return document.createElement(d.type); })
    .text(function(d) { return d.value; });
```

**Comment by NonPolynomial** [comment]
ahhh, omg, I was so blind! :D
Yes, I wanted to avoid the wrapping `div`.
Thanks a lot. Your second example is exactly what I need.

I never thought of extending the data or using a function in `.append()`!
