### ISSUE TITLE
Did 1.3 break d3-zoom?

### ISSUE THREAD

**Issue by jacobp100** [d3/d3-selection#162]
I updated to `d3-selection` 1.3; however,. It seems to have broken `d3-zoom`.

I copied and pasted the code from [here](https://bl.ocks.org/mbostock/db6b4335bf1662b413e7968910104f0f) into a stackbitz example.

https://stackblitz.com/edit/react-kzxyfx?file=index.js

**Comment by mbostock** [comment]
Perhaps you are including multiple versions of d3-selection in your dependencies, which could cause d3-zoom to have its own internal copy of d3-selection rather than the one specified at the top level of your application?

I would avoid mixing the `d3` default bundle together with the D3 submodules such as `d3-selection` and `d3-zoom`; either using the default bundle or use the submodules, not both (and if you are in a modern environment and using a bundler, definitely prefer the submodules).

**Comment by peter-poki** [comment]
I have also problem with version 1.3, it really seems to break d3-zoom.

Here is a example of one error
https://stackblitz.com/edit/react-vm4eb6?file=index.js
(its a modified example of https://bl.ocks.org/mbostock/4e3925cdc804db257a86fdef3a032a45 )

Also I suspect the new release, because everything worked before weekend, but after we run new automated builds, application is broken. And I could not simulated it locally, because I had node modules already downloaded. But when I did yarn install I got the same problem. that is becasue d3-zoom has in his dependencie "d3-selection": "1", which overtakes my 1.2 version with new version 1.3

I have locally in bigger setup also problem like this
![image](https://user-images.githubusercontent.com/22402252/35576347-0a2c5a0a-05df-11e8-9988-19d4ae1f59c0.png)

Do you have any ideas?

**Comment by mbostock** [comment]
Fixed in 5.0; see d3/d3#3256.
