### ISSUE TITLE
Suggestion:  add update method

### ISSUE THREAD

**Issue by GordonSmith** [d3/d3-selection#176]
Add "update()" method to selectAll response where:
```
update() {
  return this.enter().merge(this);
}
```
Rationale:  This is not because I am lazy, but when learning d3 I found the overloaded nature of selection  to be unnatural (and confusing).

IOW When explaining the data join pattern to a new user this:
```javascript
  const options = d3.selectAll("#mySelect").data(optionsData);
  options.enter().append("option");
  options.update()
    .property("value", d=>d.value)
    .text("value", d=>d.label);
  options.exit().remove()    
```
Is easier to understand than:
```javascript
  const options = d3.selectAll("#mySelect").data(optionsData);
  options.enter().append("option");
  options.enter().merge(options)  //  Why am I merging the enter items with the response of a selectALL?  
    .property("value", d=>d.value)
    .text("value", d=>d.label);
  options.exit().remove()    
```

**Comment by mbostock** [comment]
Unfortunately none of the patterns you suggest work, for a few reasons.

First, you would be merging the *update* selection with the *enter* placeholders rather than the materialized nodes returned by *enter*.append. 

Second, you need to set a parent node into which you’re appending: select, then selectAll.

Also, *selection*.text takes a single argument. :wink:

A corrected snippet is:

```js
// Perform the data join and obtain the update selection.
const option = d3.select("#mySelect")
  .selectAll("option")
  .data(optionsData);

// Append the entering nodes, and obtain the enter selection.
const enter = option.enter().append("option");

// Merge entering and updating nodes to apply some operations to both.
enter.merge(option)
    .property("value", d => d.value)
    .text(d => d.label);

// Remove the exiting nodes.
option.exit().remove();
```

As to the question

> Why am I merging the enter items with the response of a selectALL?  

You’re not merging it with the return value of [*selection*.selectAll](https://github.com/d3/d3-selection/blob/master/README.md#selection_selectAll), you’re merging it with the return value of [*selection*.data](https://github.com/d3/d3-selection/blob/master/README.md#selection_data), which is the updating nodes. And you’re doing that so that you can apply operations to both the entering and updating nodes. For more on data joins, see [Thinking with Joins](https://bost.ocks.org/mike/join/).

We could have an “enter-update” method which appends the entering nodes *and* merges them with the updating ones, but then you wouldn’t have an opportunity to apply some operations just to the entering nodes or some just to the updating nodes—which is the main purpose of the data join. That said, if you like convenience methods like this for specific cases of the data join, I recommend [d3-jetpack](https://github.com/gka/d3-jetpack).
