### ISSUE TITLE
Traverse back up the svg chain

### ISSUE THREAD

**Issue by Dakkaron** [d3/d3-selection#177]
I have an use case where I need to add multiple elements to an object, but I cannot directly do that using the svg chain syntax, because it only allows me to traverse it deeper into the object.

So basically, this is what I want to do:

```
defs.append("marker")
    .attr(..., ...)
    .append("svg:path")
        .attr("d", ...)
        .goUp()
    .append("svg:path")
        .attr("d", ...)
        .goUp()
    .append("svg:path")
        .attr("d", ...);
```

But I cannot do that. I know, there is a workaround by saving the marker as a variable:

```
var marker = defs.append("marker")
    .attr(..., ...);
marker.append("svg:path")
        .attr("d", ...);
marker.append("svg:path")
        .attr("d", ...);
marker.append("svg:path")
        .attr("d", ...);
```

But that has a few caveats. It looks ugly and breaks with the beautiful Domain Specific Language-like chain syntax, but it also leaves unwanted and unnecessary temporary variables behind. In my specific use case, this appears in the initialisation code in global scope. `defs` is a variable in global scope and I could easily do all of that in global scope without having to worry about anything. But the workaround would leave the unnecessary variable `marker` behind in global scope.

There is another workaround:

```
d3.select(d3.select(defs.append("marker")
    .attr(..., ...)
    .append("svg:path")
        .attr("d", ...)
        .node().parentNode)
    .append("svg:path")
        .attr("d", ...)
        .node().parentNode)
    .append("svg:path")
        .attr("d", ...);
```

This does not leave behind any temporary variables, but it is even uglier. Especially if you want to chain many appends, this can easily get out of hand.

With a simple `goUp()` function (or whatever might be a better name for that) the chain syntax could be used as a DSL that would work almost the same as svg itself.

I made this polyfill that fixes this situation: `d3.selection.prototype.goUp = function () { return d3.select(this.node().parentNode); }`

**Comment by mbostock** [comment]
This feature has been previously discussed in the d3/d3 repository issues which unfortunately I had to close due to repeated abuse.

One of the challenges is that *selection*.select propagates data, and when going from the child to the parent, you rarely want this behavior. And secondly [selections are nested](https://bost.ocks.org/mike/nest/) (see [How Selections Work](https://bost.ocks.org/mike/selection/)), and there’s no way to reconstruct the parent structure just by doing select.

You could perhaps keep a stack of selections in *selection*.select and *selection*.selectAll so that you can pop them off the stack to get back the originating selection, but I don’t think you want this in the default case because it could be easy to leak memory by keeping references to selections that you’re no longer using.

Also, as a more opinionated issue, I think method chaining is easy to overuse, and that you typically get more readable code by keeping local variables or by using *selection*.call. For example:

```js
defs.append("marker")
    .attr(…)
    .call(marker => marker.append("path").attr(…))
    .call(marker => marker.append("path").attr(…))
    .call(marker => marker.append("path").attr(…));
```

I have no plans to implement this feature, but the d3.selection.prototype is extensible so you are welcome to write your own D3 module that adds additional methods for more flexible chaining. See also [d3-jetpack’s parent method](https://github.com/gka/d3-jetpack/blob/master/README.md#parent).
