### ISSUE TITLE
Importing d3-selection causes errors

### ISSUE THREAD

**Issue by visusnet** [d3/d3-selection#181]
The following error message occurs when d3-selection is imported in a test environment before JSDOM (or any other mocked DOM) has initialized its global objects:
```
Cannot read property 'matches' of undefined
at node_modules/d3-selection/build/d3-selection.js
```
This is due to the eager initialization of the matcher function. Merely importing d3-selection should not cause problems.

**Comment by mbostock** [comment]
It’s already the case that detection for native *element*.matches support isn’t run if the global `document` is not available:

https://github.com/d3/d3-selection/blob/679346930e41a4037ef72d937b425bbe4d865ab1/src/matcher.js#L7

So, it doesn’t feel to me like the eager initialization (in the case a global `document` is available) is the problem here; it’s something else that’s actually invoking the initialized matcher function, only to find that the element on which you are matching doesn’t support *element*.matches.

D3 is not a compatibility layer, so I think it’s time to remove the fallback for vendor-prefixed *element*.matches, and rely on [native support](https://caniuse.com/#feat=matchesselector) for it #187. That eliminates the need for any initialization, though you’ll still get the error above if you’re using an old version of JSDOM or an old browser that doesn’t support *element*.matches.

**Comment by mbostock** [comment]
(I’ll reopen and investigate further if you can give me a test case to reproduce the error.)
