### ISSUE TITLE
d3Selection.pointer does not work on mobile device

### ISSUE THREAD

**Issue by stoneshell** [d3/d3-selection#270]
event.clientX, event.clientY are undefined.
![1606265752401](https://user-images.githubusercontent.com/38196682/100169083-90732180-2efd-11eb-95b9-041b63033cfc.jpg)

Maybe get the values from event.touches ?
![1606265926164](https://user-images.githubusercontent.com/38196682/100169168-c44e4700-2efd-11eb-9dd4-fefcb5c749b0.jpg)

**Comment by mbostock** [comment]
Please read the documentation:

https://github.com/d3/d3-selection/blob/master/README.md#pointer

You need to pass a Touch to d3.pointer, not a TouchEvent. Also see d3.pointers.

**Comment by HarelM** [comment]
I migrated to latest version and also suffered from this mistake.
But moreover, I'm listening to both touch and mouse and I'm passing the `e.touches[0]` in case of touch and `e` in case of mouse.
The problem is that the `currentTarget` for `Touch` does not exists so passing `Touch` to `pointer` will result in an unwanted behavior.
While I understand I can pass the `e.currentTarget` it would be helpful to write it in the docs linked above or even in the method description to prevent other developers from creating a bug :-)

**Comment by HarelM** [comment]
So basically my code looks like this when using `pointer`
```
const expectedEvent = (window.TouchEvent && e instanceof TouchEvent) ? e.touches[0] : e;
return this.chartElements.xScale.invert(d3.pointer(expectedEvent, e.currentTarget)[0]);
```
