### ISSUE TITLE
d3.style('padding') or d3.style('margin') returned empty string only in firefox

### ISSUE THREAD

**Issue by ZaharovDm** [d3/d3-selection#290]
in Firefox
![image](https://user-images.githubusercontent.com/17457553/127151242-5f4145b5-8de9-4087-b290-65144240ac65.png)

in Google

![image](https://user-images.githubusercontent.com/17457553/127151331-219bd924-7e11-4c76-8ada-17a0316f127f.png)

**Comment by mbostock** [comment]
You can see what *selection*.style returns here:

https://github.com/d3/d3-selection/blob/91245ee124ec4dd491e498ecbdc9679d75332b49/src/selection/style.js#L34

If Firefox returns an empty string, it’s because Firefox defines that as the computed value. D3 is not a compatibility layer, so it does not include workarounds to normalize different behaviors across browsers.

I suspect the problem here is that the G element is an SVG element, where the HTML styles of margin and padding do not make sense. These styles have no effect on layout within an SVG element; you must use the transform attribute to change how a G element is positioned. I suspect that Firefox does not compute HTML styles on SVG G elements, whereas other browsers may (even though they have no effect).
