### ISSUE TITLE
Data join without DOM?

### ISSUE THREAD

**Issue by nitaku** [d3/d3-selection#45]
I don't know if this is the right time or place to ask this, but... Have you ever considered to generalize the data join mechanism to work with something other than the DOM? I'm thinking about using it with 3D objects in [three.js](http://threejs.org/), markers in [Leaflet](http://leafletjs.com/), or even canvas, by specifying custom functions to handle creation, update and deletion of stuff.

Do you think it would be feasible / useful?

**Comment by mbostock** [comment]
There are a few tricks that might be helpful.

You can use custom DOM elements to represent your scenegraph, and then write code to render this however you like to canvas whenever the DOM changes: http://bl.ocks.org/mbostock/1276463 (That example uses d3.timer to redraw continuously, but with some additional effort you could make it more efficient.)

You can use X3DOM: http://bl.ocks.org/hlvoorhees/5986172 I believe this technique is similar to the above, but I don’t know how X3DOM is implemented.

You can select arbitrary objects rather than elements, say to manage transitions rendered to Canvas without using the DOM: http://bl.ocks.org/mbostock/9539958

More generally, I think it’s reasonable to apply the concepts of D3 to other types of scenegraphs. But I don’t think it makes sense to try to make d3-selection more generic than it already is—my intuition is that this could make the API harder to use in the common case of using the DOM. So, if you are interested in this approach I would start by making a fork or building something D3-like from scratch. If you discover an elegant approach, by all means let me know and we can discuss whether it’s something that makes sense to merge back in. :grin:

**Comment by nitaku** [comment]
Thanks a lot, I'll have a look at the examples and think about ways to accomplish what I suggested. If I come up with something worthwhile, I'll let you know. :)

**Comment by curran** [comment]
@nitaku For what it's worth, I recently tried working with Leaflet for interactive visualizations and have run into exactly this issue - I found myself wishing I could use the D3 enter/update/exit logic applied to Leaflet markers.

Here's an example that illustrates the need: [Migrant Deaths over Time](http://bl.ocks.org/curran/a479b91bba14d633487e).

[![thm](https://cloud.githubusercontent.com/assets/68416/12072053/1017de08-b09b-11e5-8795-3336da734460.png)](http://bl.ocks.org/curran/a479b91bba14d633487e)

Brushing in the date view filters the data shown in the map view. In this implementation, all the markers are removed and new ones are re-created every time the user brushes. This is a quick and dirty solution, and I thought about implementing a D3-like enter/update/exit sort of thing to improve the performance.

However, ultimately it may be best to use D3 for the map component as well and not use Leaflet at all, which I think is the direction I'm heading for future work.
