### ISSUE TITLE
Documentation on classed changes

### ISSUE THREAD

**Issue by pshrmn** [d3/d3-selection#62]
Should there be a note on the `classed` documentation to state that passing it an object no longer is an option? While it can be inferred that that is the case (from that option not being documented), the change will break old code since the single object argument will return a boolean value instead of a selection. Having that change explicitly stated will probably be useful for people who run into this issue.

**Comment by mbostock** [comment]
The multi-value methods have been moved to [d3-selection-multi](https://github.com/d3/d3-selection-multi) as an optional add-on, and have been renamed to their plural form to avoid ambiguity. However, not all multi-value methods have yet been implemented, including *selection*.classed and transition methods.

When D3 4.0 is closer to release, I will be writing release notes that cover all changes since 3.x, along with a 3-to-4 migration guide. (The API reference only covers the current version of the code.) I previously maintained a list of changes incrementally during the development of 4.0, but I found it overly tedious to describe changes as they were being made; hence my decision to postpone documentation of changes until the API is finalized at release.
