### ISSUE TITLE
Apply content operators used as getters to all elements of the selection

### ISSUE THREAD

**Issue by mindrones** [d3/d3-selection#66]
*(asking here as what I'm suggesting would break compatibility with d3 v3)*

**Use case example**

Say we want to get all `a` texts from https://d3js.org.

As stated in the [doc](https://github.com/mbostock/d3/wiki/Selections#text), `d3.selectAll('a').text()` returns `"Overview"`, that is, the text of the first non-null element in the selection.

To get them all, we can do:
```js
var texts = []
d3.selectAll('a').each(function(d, i) {
  texts.push(d3.select(this).text())
})
```
(or maybe there's a `selection` API to do this that I'm not aware of?)

Instead, I'd like to use `.text()` to get them all and continue manipulating the array by chaining, say 
`var texts = d3.selectAll('a').text().sort().map(...)`.

**Applicability**

Excluding `append`, `insert`, and `remove`,  this would be useful on almost all [content operators](https://github.com/mbostock/d3/wiki/Selections#content):
- [selection.attr](https://github.com/mbostock/d3/wiki/Selections#attr): 
  `selection.selectAll('a').attr('href')  // => ['#foo', 'https://foo.org', ...]`

- [selection.classed](https://github.com/mbostock/d3/wiki/Selections#classed): 
  `selection.selectAll('div').classed('foo')  // => [true, false, ...]`

- [selection.style](https://github.com/mbostock/d3/wiki/Selections#style): 
  `selection.selectAll('path').style('stroke')  // => ['black', none, ...]`

- [selection.property](https://github.com/mbostock/d3/wiki/Selections#property):
  `selection.selectAll('input').property('checked')  // => [false, false, ...]`

- [selection.text](https://github.com/mbostock/d3/wiki/Selections#text): 
  `selection.selectAll('a').text()  // => ["Overview", "Examples", ...]`

- [selection.html](https://github.com/mbostock/d3/wiki/Selections#html): 
  `selection.selectAll('div').html()  // => ["<p>foo</p>", ["<p>bar</p>", ...]`

**Proposals**

It would be handy to have these operators apply to all elements of the selection.

In alternative, it would be nice to have a `selection.map()` method that can return things different from a selection:

  ```js
selection.selectAll('a').map(function(d, i) { return d3.select(this).text() })
// => ["Overview", "Examples", ...]
selection.selectAll('div').map(function(d, i) { return d })
// => [{a: 1} , {a: 2}, ...]
  ```
  (maybe `map` is not ideal, could be something else)

**Comment by mbostock** [comment]
Here’s how you’d implement the proposed *selection*.map:

```js
d3.selection.prototype.map = function(f) {
  var array = [];
  this.each(function() { array.push(f.apply(this, arguments)); });
  return array;
};
```

For the first example you gave, using *node*.textContent would be a bit faster than creating a single-element selection for each element:

```js
selection.selectAll("a").map(function() { return this.textContent; });
```

However, it’s not really necessary to add *selection*.map because you can chain with *selection*.nodes as described in mbostock/d3#2696:

```js
selection.selectAll("a").nodes().map(function() { return this.textContent; });
```

For the second example, you can already use *selection*.data to retrieve all nodes’ data (unlike *selection*.datum, which just returns the datum of the first non-null element, similar to how *selection*.attr returns the attribute value of the first non-null element):

```js
selection.selectAll("data").data();
```

Regarding *selection*.map, a little bit of history. What is now *selection*.datum was originally called *selection*.map (see mbostock/d3#45), and it was used for re-assigning the data bound to the selected elements. After the rename, we considered adding a new *selection*.map in 3.0 that behaves as you describe; however, it didn’t seem sufficiently useful to include at the time. There have been a couple requests for a *selection*.map method as you describe here (see mbostock/d3#878 and mbostock/d3#2696), but personally I’m inclined to just chain with *selection*.nodes for the sake of parsimony.
