### ISSUE TITLE
.attr(object) no longer works

### ISSUE THREAD

**Issue by umbra268** [d3/d3-selection#69]
.attr(object) which works in the previous version of d3 doesn't appear to work in this version.

Instead of it returning the selection it appears to return a null property value as the namespace function returns "[object Object]".

**Comment by jimkang** [comment]
That's been removed from the d3-selection core, but you can get it by using the [d3-selection-multi plugin](https://github.com/d3/d3-selection-multi). You just `require` it after requiring `d3-selection`, and it adds that behavior.

**Comment by mbostock** [comment]
Correct. Thanks for answering, @jimkang.

The multi-value methods have been moved to [d3-selection-multi](https://github.com/d3/d3-selection-multi) as an optional add-on, and have been renamed to their plural form to avoid ambiguity. However, not all multi-value methods have yet been implemented, including *selection*.classed and transition methods.

When D3 4.0 is closer to release, I will be writing release notes that cover all changes since 3.x, along with a 3-to-4 migration guide. (The API reference only covers the current version of the code.) I previously maintained a list of changes incrementally during the development of 4.0, but I found it overly tedious to describe changes as they were being made; hence my decision to postpone documentation of changes until the API is finalized at release.
