### ISSUE TITLE
index not being passed to child element accessors

### ISSUE THREAD

**Issue by davelandry** [d3/d3-selection#73]
Not sure if this is a bug or expected behavior, but when I run the following code it prints out `0` for each index ([CodePen](http://codepen.io/anon/pen/oxKrMp?editors=1011)):
```js
var p = d3_selection.select("body").selectAll(".parent").data([0, 1]);

var enter = p.enter().append("div").attr("class", "parent")
enter.append("div").attr("class", "child");

p = p.merge(enter);

p.selectAll(".child").style("color", function(d, i) {
    console.log(d, i);
    return "red";
});
```

I'm assuming that's because each child element is the first index inside of their respective parents? Is there a way to get the index of the original data array?

**Comment by mbostock** [comment]
> I'm assuming that's because each child element is the first index inside of their respective parents?

Yes, this is expected. See [How Selections Work](https://bost.ocks.org/mike/selection/) and [Nested Selections](https://bost.ocks.org/mike/nest/).

If there’s only one child for each parent, the simplest way to preserve the child index (and to propagate the data from the parent to the child) is to use [*selection*.select](https://github.com/d3/d3-selection#selection_select) rather than [*selection*.selectAll](https://github.com/d3/d3-selection#selection_selectAll).

```js
p.select(".child").style("color", function(d, i) {
  console.log("child data and index", d, i);
  return "red";
});
```

If there are multiple children for each parent, one option is to add the parent’s index to the children’s data (which is basically what you are already doing with `d` instead of `i`). Or you can use [*selection*.each](https://github.com/d3/d3-selection#selection_each) to create a context where you can access both the parent’s data and index, and the child’s data and index, simultaneously:

```js
p.each(function(p, j) {
  d3_selection.select(this).selectAll(".child").style("color", function(d, i) {
    console.log("parent data and index", d, i);
    console.log("child data and index", d, i);
    return "red";
  });
});
```

Of course, *selection*.select is the simplest option for 1-to-1 relationships between parent and child.

**Comment by davelandry** [comment]
Thanks for the thorough response!
