### ISSUE TITLE
d3.select(d3.selection) - just return the selection

### ISSUE THREAD

**Issue by IPWright83** [d3/d3-selection#76]
I've had a quick look at the code and I _don't think_ it's doing this already from my understanding of it, but it'd really helpful if `d3.select()` could take a selection, and not throw errors later on the down the line. 

The use case for this is when you're composing visualizations. For example if I create something like a force-directed I may have some DOM that looks like:

```
<svg>
   <g class="node"/>
   <g class="node"/>
   <g class="node"/>
</svg>
```

Within each of these groups, I now want to add another visualization - say a pie chart. Within some sort of pie chart component I want to be able to do:

```
var Pie = function(target) {
   d3.select(target).append("g");
}
```

This would work if I provided `"svg"` as the `target` but not if I provided a selection like:

```
d3.selectAll("g")
   .each(function(d) { new Pie(this) });
```

I use a small filler to handle this situation, as it makes creating the visualizations much simpler, but it'd be really great if this were just included (I don't like replacing `d3.select` really):

```
/*
 * Re-define the d3.select function so that it can handle the case where a
 * selection is passed to the function.
 */
(function () {

    // Save a reference to the original d3.select function
    var select = d3.select;

    // Re-define select
    d3.select = function (selector) {
        // If the selector is already a selection, just return it
        // otherwise call the original d3.select function
        if (selector instanceof d3.selection) return selector;
        return select(selector);
    };
})();
```

**Comment by curran** [comment]
I also ran into this when attempting to build an API that would accept either a raw DOM element or a selection.

**Comment by mbostock** [comment]
Sorry, but I don’t think it’s a good idea to overload d3.select in this way. d3.select has a very specific meaning: it selects exactly one node. (See [select.js](https://github.com/d3/d3-selection/blob/master/src/select.js).) You either pass that one node in explicitly, or it is selected implicitly via a selector string or a function.

Changing d3.select to be the identity function because you passed in a selector seems… weird and magical. Although it may seem convenient to design an API this way, I believe it would be confusing. I wrote about a closely-related case in [What Makes Software Good?](https://medium.com/@mbostock/what-makes-software-good-943557f8a488#.whyjz2s1h); see Case 3.

My recommendation is to design components to always take selections, as I wrote in [Towards Reusable Charts](https://bost.ocks.org/mike/chart/), and to invoke the component via *selection*.call or *transition*.call. Some examples of this technique in D3:

https://github.com/d3/d3-axis/blob/master/src/axis.js
https://github.com/d3/d3-brush/blob/master/src/brush.js
https://github.com/d3/d3-zoom/blob/master/src/zoom.js

A subtle consequence of this technique is that components take selections with *multiple* elements, not just a single element, and thus when you *selection*.call them, then render multiple charts (or whatevers) simultaneously, like a rubber stamp. Your component can also look at the data bound to each element to affect the display.

```js
d3.selectAll("node").call(pie);
```

You can use function accessors to allow the caller to customize the appearance of each component on a per-node basis, or you can simply rely on them to invoke the component separately (say with *selection*.each).

If you really want this feature, I’d define them as separate functions:

```js
function maybeSelect(selector) {
  return selector instanceof selection ? selector : select(selector);
}

function maybeSelectAll(selector) {
  return selector instanceof selection ? selector : selectAll(selector);
}
```

But, whenever I see code like that I usually think it’s better to have the caller do the instanceof check, so that the resulting code is more obvious. The d3-axis component, for instance, looks for *transition*.selection to distinguish whether the input group is a transition or a selection.
