### ISSUE TITLE
selection.selectNone? selectData?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-selection#79]
It might be useful (and cleaner) than the standard pattern of selecting elements that you know don’t exist. So instead of this:

```js
d3.select("body")
  .selectAll("div") // Assumed to be empty.
  .data(["foo", "bar", "baz"])
  .enter().append("div")
    .text(function(d) { return d; });
```

You’d say:

```js
d3.select("body")
  .selectNone()
  .data(["foo", "bar", "baz"])
  .enter().append("div")
    .text(function(d) { return d; });
```

But is there any other time where you deliberately what to select none? It’s probably only useful followed by *selection*.data and *selection*.enter, so perhaps you could instead say:

```js
d3.select("body")
  .selectData(["foo", "bar", "baz"])
  .append("div")
    .text(function(d) { return d; });
```

So, *selection*.selectData(*data*) is an alias for *selection*.selectAll(*none*).data(*data*).enter().

**Comment by cpietsch** [comment]
And what if the _selection.data_ returns an selectAll & enter if called not on a NodeList?

```
d3.select("body")
  .data(["foo", "bar", "baz"])
  .append("div")
    .text(function(d) { return d; });
```

**Comment by seliopou** [comment]
Not entirely sure what this is supposed to do. Is it equivalent to this?

```javascript
d3.select("body")
  .selectAll(":not(*)")
  .data(["foo", "bar", "baz"])
  .enter().append("div")
    .text(function(d) { return d; });
```

If it is, then the idea's good but the names are very confusing. The clearest way to do it would be to use a CSS selector that matched no elements. Like `":not(*)"`, but a little less arcane. Maybe `"none"`, `"nothing"`, but then the problem is of course... they're not actually CSS selectors.

**Comment by mbostock** [comment]
@cpietsch That makes the behavior of *selection*.data modal, which would be confusing.

**Comment by mbostock** [comment]
@seliopou It is exactly equivalent to this:

```js
d3.select("body")
  .selectAll(function() { return []; })
  .data(["foo", "bar", "baz"])
  .enter().append("div")
    .text(function(d) { return d; });
```

That’s basically equivalent to `document.body.querySelectorAll(":not(*)")`, but it’s slightly faster.

Do you find *selection*.selectNone or *selection*.selectData confusing? I’d only include one of the two, if any. A *selection*.selectData method would result in shorter code, but *selection*.selectNone is closer to what is done now and more consistent / parsimonious with the data-join pattern.

**Comment by seliopou** [comment]
I think `selection.selectData` is confusing. I totally get where you were going with the name&mdash;signifying that the function straddles to two concepts&mdash;but when I first saw it, it was unclear to me which selection was participating in the data join. Is it the one that `selectData` is called on (my first gut reaction) or some other sub- or related-selection?

`selection.selectNone` definitely preserves the conceptual fidelity of the library, but is just kind of awkward to read.

What about just `selection.selectAll()`? No arguments? Could be interpreted as selecting either everything or nothing. But asserting in the docs that it selects nothing could be a nice way forward.

**Comment by tophtucker** [comment]
I am weakly opposed for reasons I find hard to articulate even to myself. The enter/update/exit pattern is quite beautiful. It increases the barrier to entry when you just want to append some things, but compels a good data binding mindset.

Seconding @seliopou, doesn't `selection.selectAll()` already work? Seems like it...

```
d3.select("body")
  .selectAll()
  .data(["foo", "bar", "baz"])
  .enter().append("div");
```

**Comment by NelsonMinar** [comment]
have you considered `selectAll(null)`? Perhaps that already has a different meaning? I like `selectAll()` too.

**Comment by mbostock** [comment]
I think it’d be reasonable for these to all be equivalent to the proposed *selection*.selectNone:

```js
selection.selectAll()
selection.selectAll(null)
selection.selectAll(undefined)
```

Currently the selector is coerced to a string (by *element*.querySelectorAll), so they are actually equivalent to these:

```js
selection.selectAll("undefined")
selection.selectAll("null")
selection.selectAll("undefined")
```

In practice, you’re unlikely to have a `<null>` or `<undefined>` element, but I think having it always be empty when the *selector* is nully is better than coercing it to a string.

**Comment by mbostock** [comment]
I’ve changed the behavior of d3.select, d3.selectAll, *selection*.select and *selection*.selectAll so that if the selector is null, the resulting selections are always empty, rather than coercing the null or undefined selector to the string “null” or “undefined”. That seems like a no-brainer improvement, and obviates the need for a new *selection*.selectNone method.

That leaves a place for *selection*.selectData, though, but I kinda agree with Toph… It’s good to have only one way of doing things. And at least now you can *selection*.selectAll() if you want to force all the data into enter regardless of the DOM.

**Comment by IsaKiko** [comment]
This might be a bit controversial, but I find my students also have a problem understanding why '.data' is called '.data'.
It seems you could kill two birds with one stone having the data and the page elements in here:
.bind('.classname',data,function(d){keyfunction})
This doesn't necessarily suggest that elements '.classname' already exist.

**Comment by jeinarsson** [comment]
In my opinion

```javascript
d3.select("body")
  .selectData(["foo", "bar", "baz"])
  .append("div")
    .text(function(d) { return d; });
```

is more understandable than

```javascript
d3.select("body")
  .selectAll() // empty, according to new behavior
  .data(["foo", "bar", "baz"])
  .enter().append("TYPO")
    .text(function(d) { return d; });
```

Second, I did not immediately understand the name "selectData". The action is "create entering selection from data". Perhaps `.selectionFromData`, `.enterFromData`, or something along those lines? 

Is the following readable?

```javascript
d3.select("body")
  .selectionFromData(["foo", "bar", "baz"])
  .append("div")
    .text(function(d) { return d; });
```

**Comment by curran** [comment]
I would prefer to see 

```js
d3.select("body")
  .selectAll() // empty, according to new behavior
  .data(["foo", "bar", "baz"])
  .enter().append("div")
    .text(function(d) { return d; });
```

rather than

```js
d3.select("body")
  .selectData(["foo", "bar", "baz"])
  .append("div")
    .text(function(d) { return d; });
```

because the first is a familiar API to me. I'm biased by having used D3 for a while, but when I see `selectData`, I feel like "oh no, there's now more surface area of the API that I need to take time and learn". I would agree that, as @mbostock says "It’s good to have fewer ways of doing things.".

**Comment by tomwanzek** [comment]
I would agree with @mbostock, @curran, and @tophtucker. A simple, consistent mental model of coding enter/update/exit patterns is preferable:

- `selectAll`: select elements with their existing data, where they exist
- `data`: change data/perform data join and expose the resulting _update_, _enter_, and _exit selections_ for further action depending on use case at hand
- `append`/`insert`: add materialized DOM elements with data from parent.

There is an inherent clarity of purpose in the above. `selectData` feels like fusing two lego blocks of the mental model, when there is no material gain to be had.

**Comment by GordonSmith** [comment]
IMO This would encourage folks to write visualizations that _cant_ be resized or refreshed.  Currently most of the work involved porting a visualization from blocks to the real world is moving attr calls from enter() to update.

But since we are throwing out suggestions how about:
```
d3.select("body")
  .join("css selector", ["some", "data"], function(d) {return "d.identity";})
  .enter().append("div")
...
```

**Comment by mbostock** [comment]
Thanks for all the feedback! It’s extremely helpful to hear different perspectives, and I’m happy we discovered an improvement to *selection*.select and *selection*.selectAll to more closely match expected behavior.

I think for now it’s best to stay conservative and not introduce a new method. 4.0’s [new module pattern](https://bost.ocks.org/mike/d3-plugin/) will hopefully make it easier for people to use API extensions like @gka’s [d3-jetpack](https://github.com/gka/d3-jetpack) and @1wheel’s [d3-starterkit](https://github.com/1wheel/d3-starterkit). I’d love to see more of these in the future, and then usage can help drive improvements to the default API.

Related to that, if someone wants to get started on a web-based [custom bundler](https://bl.ocks.org/mbostock/97557a39b4bfc8229786c8bccb54074d), that would be extremely helpful! It could either let you choose at the module level and simply cat them together, or it could be really fancy and run Rollup in the browser and let you choose at the symbol level.

**Comment by curran** [comment]
I took a stab some time back at a D3 custom bundler UI https://github.com/curran/d3-bundler-ui . Unfortunately I have not had time to devote to it, but what's there does work, and there may be ideas there that folks can draw from to start a new, upgraded initiative.

For example, here's the snippet that generates the ES6 index.js:

```js
  return function (modulesToInclude){
    return [
      modulesToInclude.map(function (module){
        return modules[module].import;
      }).join("\n"),
      "",
      "export default {",
      modulesToInclude.map(function (module){
        return "  " + modules[module].export;
      }).join(",\n"),
      "};"
    ].join("\n");
  };
```

The above code references this index of module imports and exports, which I found to be required to accommodate slight differences across modules (perhaps not necessary anymore after all the development on 4.0):

```json
{
  "event": {
    "import": "import { event } from \"d3-selection\";",
    "export": "get event() { return event; }"
  },
  "select": {
    "import": "import { select } from \"d3-selection\";",
    "export": "select: select"
  },
  "selectAll": {
    "import": "import { selectAll } from \"d3-selection\";",
    "export": "selectAll: selectAll"
  },
  "selection": {
    "import": "import { selection } from \"d3-selection\";",
    "export": "selection: selection"
  },
  "transition": {
    "import": "import { transition } from \"d3-transition\";",
    "export": "transition: transition"
  }
}
```

Here's what the [UI](https://dry-tundra-5462.herokuapp.com/) looks like

[![](https://camo.githubusercontent.com/48ee5c90c8f7812ee588f7eeeef6ef6678235993/687474703a2f2f63757272616e2e6769746875622e696f2f696d616765732f64332d62756e646c65722d75692f70726f746f747970652e706e67)](https://dry-tundra-5462.herokuapp.com/)

**Comment by seliopou** [comment]
Just to follow-up on @IsaKiko's `bind` suggestion, I have gotten requests for this multiple times for my [elm-d3](https://github.com/seliopou/elm-d3) and [ocaml-d3](https://github.com/seliopou/ocaml-d3) bindings. Not only is it seen as more user-friendly, but it also has consequences related to the typing rules. Separating the construction of a selection and the application of a data bind is in general not sound with respect to reasonable typing rules, where as fusing them together in a `bind` like operation is always sound.

**Comment by mbostock** [comment]
@curran I’ve filed d3/d3#2861 to talk about custom bundlers. Anyone who is interested let’s discuss over there.

**Comment by myadhdoutlet** [comment]
I agree that the assumption and legibility of the empty selection is a somewhat opaque stumbling block for many; how about the option to combine data() and enter() when you intend to initially introduce data-bound elements to the DOM rather than combining select() and data() before enter()? 

e.g.,

`d3.select("body")
  .enterData(["foo", "bar", "baz"])
  .append("div")
    .text(function(d) { return d; });`

or, maybe like this, (which I find to be less clear and don't like as much):

`d3.select("body")
  .enter(["foo", "bar", "baz"])
  .append("div")
    .text(function(d) { return d; });`

**Comment by tungs** [comment]
Just wanted to add (too late to the discussion) that when I started learning d3, I found the empty selection before the `.data` statement to be the most confusing part of the data binding process. It seemed to me that a more intuitive syntax would be similar to the `selectData`, except in my mind, it'd be `withData`:

```
d3.select("body")
  .withData(["foo", "bar", "baz"])
  .append("div")
    .text(function(d) { return d; });
```

**Comment by jeinarsson** [comment]
@curran @mbostock  I have much respect for the "one way to do things" argument, and _if in doubt - hold_ seems a good strategy.

At any rate,

@tungs +1 for `.withData` name

I also in principle agree with @GordonSmith that the api should encourage updateable charts, and so forth. But in practise I've found myself making some parts of a larger figure non-updateable, eg some UI elements, whereas eg sub-charts are updateable on UI events. For the parts that I don't intend to update I definitely find the `.withData` syntax appealing.

**Comment by myadhdoutlet** [comment]
I was initially tempted to think along the lines of @tungs, but if you think critically about how selections, data binding, and `enter()`/`leave()`/`exit()` work, `selectAll(null)` appears to be a better, more semantically consistent solution. 

If anything, it would make more sense for the approach you suggest to be named something like `emptySelectionWithData()`.

**Comment by aschneiderman** [comment]
I really appreciate the desire for parsimony, but clairty matters too.  Having to select nothing in order to create something is just weird.  It's particularly an issue for beginners.  If you want d3 to grow, figuring out to reduce the cognitive load of getting started is pretty important.  And givne that a awful lot of examples that get folks interested in learning d3 just use enter and don't update/exit, requiring that all of these examples select nothing in order to create anything isn't helping.

**Comment by monfera** [comment]
On small projects, one can use the selection pattern in arbitrary ways, for example as in Mike's description:
```
d3.select("body")
  .selectAll("div") // Assumed to be empty.
  .data(["foo", "bar", "baz"])
  .enter().append("div")
    .text(function(d) { return d; });
```
Note the absence of two things:

- setting the class on the newly created `<div>` elements
- using a `key` function as a second argument to `.data()`

I found that these two steps can be omitted on very small projects, but if it grows, or the task is larger to begin with, then it's good practice to always use them. So my normal pattern uses even more broilerplate than the above, whether I strictly need it or not (takes off the burden of assumptions):
```
d3.select("body")
  .selectAll(".countryItem") // always select by class, not by DOM element which may change
  .data(["foo", "bar", "baz"], keyFun)
  .enter().append("div")
    .classed(".countryItem", true) // class name in the selection repeated here
    .text(function(d) { return d; });
```
It's safer; minimal chance for selecting the wrong element, or other accident. If there's no `enter` or `exit`, code is simple either way. But if there is `enter` and `exit`, then *not* using a key function is most often a mistake. Hence my preference for the safer baseline even if it isn't always strictly needed.
So on certain projects, some in production, I defined a `bind` function, which simplifies this to something like this (pseudocode):
```
let countries = bind(body, "countryItem", ["foo", "bar", "baz"], "div")
countries.entered
  .text(d => d)
```
Benefits that apply to me:

1. most importantly, it may be a lower barrier to entry for coworkers; at least when working with less D3-experienced coders, they scratched their head about the native GUP but could use the `bind` facility straight away (mastering GUP eventually is crucial though)
2. more compact code: base case is a one-liner rather than a code block
3. a regular pattern of assigning a selection to a variable (e.g. `body` comes from an upstream `bind`), rather than relying on chaining or reselection, which can get messy or inefficient on large datavis)
4. separation of the binding + variable assignment from the `.enter()`, `.exit()` chaining: again, the conventional indentation in the customary chaining works (but editors tend to remove or lint them), but on larger tasks can become brittle
5. automatic use of the `class` for selection and setting it on the elements
6. automatic use of an implied `key` function, which for simplicity is defined as `d => d.key` but a fifth, optional argument to `bind` might overrule it if necessary
7. no need to think about whether I write, or look at (the result of) a messy, whipped-up selection that shortcuts some things or a canonical selection (defined as reliably using `class` and `key`) - it's always the latter 

Again, doesn't matter on small projects, but on large ones, the `<g>` element is used most often. Even when you put a circle on a scatterplot, it's good practice to put it in a '<g>' element as you may need to have features such as a permanent text label on the circle, or some other glyph (well, provided you aren't using the `<marker>` for repeated elements, but that's another topic...). So the argument can be made optional, defaulting to `<g>`. 

An example for the `bind` - and definitely not an example for breaking code into multiple files, or good practices in general - is here: [demo](http://www.perceptualedge.com/files/studentDashboard/) [writeup](http://retinatics.com/the-making-of-stephen-fews-student-performance-dashboard/) and [code](https://github.com/monfera/sf-student-dashboard/blob/master/render.js#L169-L216)
