### ISSUE TITLE
Suggestion: don't invoke call-ed functions on empty selections 

### ISSUE THREAD

**Issue by chrisprice** [d3/d3-selection#83]
When trying to define a recursive component I was surprised to discover that functions are always `call`-ed, even on empty selections. I am proposing that the implementation of `call` be modified to add a guard which checks `empty` before invoking the function.

Here's a cutdown example including the additional guard I was required to add -

```js
const component = (selection) => {
  if (selection.empty()) {
    return;
  }

  selection.selectAll('p')
    .data(d => d.children)
    .enter()
      .append('p')
      .text(d => d.item)
      .call(component);
};
```

As `call`-ed functions are intended to operate on the supplied `selection` I wouldn't expect this change to impact existing code as there'd be no nodes to operate on.

*It may be necessary to optimise the implementation of `empty` (which currently checks the length of `nodes`) to avoid any performance impact.*

I'm happy to make a PR for this change but wanted to discuss whether it was deemed appropriate.

**Comment by mbostock** [comment]
It’s completely valid to *selection*.call a function when the *selection* is empty. The called function is allowed to do whatever it wants. (For example, maybe it does a data-join and enter-appends elements to the empty selection.) If you don’t want your function to do something when the selection is empty, then you can check at the top of your function and then return, but this assumption shouldn’t be baked in to *selection*.call.

More generally, though, the cost of running operations on empty selections tends to be very small. D3’s data-join pattern encourages you to write code independent of how many elements there are (or whether there are elements) in a selection, rather than using explicit branching or looping statements to deal with these conditions explicitly.

**Comment by chrisprice** [comment]
Firstly just to clarify, whilst the empty check does short circuit the data join for an empty selection it's primary purpose is to terminate the recursion.

I suppose I was actually arguing in the spirit of the second paragraph by raising this issue. I'm trying to avoid explicit branching/looping by using recursion but I'm finding myself having to explicitly terminate because call runs for empty selections.

I can understand a reluctance to change it if this behaviour is now well defined, but I think not calling for empty selections would have been an equally valid design decision at the time this functionality was first added.

**Comment by mbostock** [comment]
I disagree on the last point; the purpose of selection.call is to call a function given a selection and to behave identically to calling the function directly, excepting the return value for the purposes of method chaining. So this:

```js
selection.call(foo, 42);
```

Is equivalent to:

```js
foo(selection, 42);
```

Except that the former allows chaining.

Baking in additional assumptions such as that the function should only be called if the selection is non-empty would be surprising.

It’s rare that the cost of invoking a function on an empty selection is appreciable (especially compared to DOM manipulation). If you have seen poor performance because of this design, please share some empirical evidence to show the magnitude of the issue and I will consider ways to address this.

Otherwise, if you want to optimize for empty selections, it doesn’t seem particularly onerous to check at the top of your function. If you want a primitive for this, then you can define your own helper function or extend d3.selection.prototype (and perhaps d3.transition.prototype).

**Comment by chrisprice** [comment]
That's a fair point, such a change would move it quite far from that definition and, as you say, adding the check at the top of the function isn't particularly onerous.

To reiterate, the check was not put in for any performance reasons. It was added **only** to terminate the recursive call. The short circuiting was an inconsequential side-effect. I have no concerns about the performance of data-join 👍

**Comment by chrisprice** [comment]
And thanks for taking the time to point out that definition 😄

**Comment by mbostock** [comment]
Thanks for the additional context. Could you elaborate on what you mean by recursion? Is your component calling itself recursively?

**Comment by chrisprice** [comment]
Yep, you can see that in the code snippet above. 

```js
const component = (selection) => {
// blah blah blah
      .call(component);
```

Full context, I was trying to think up an example for a blog post which demonstrates a situation we've previously fallen foul of. Before I state the problem, I should say it's not anything I think is wrong, it's just something which has previously tripped us up and I wanted to share our solution.

Here's the full (contrived) example -

```js
const root = [
  [ 1, 2, 3 ],
  [ 2, 4, 6 ],
  [ 3, 6, 9 ]
];

const component = (selection) => {
  if (selection.empty()) {
    // d3/d3-selection#83
    return;
  }

  const update = selection.selectAll('p')
    .data(d => d);

  const enter = update.enter()
    .append('p');

  update.merge(enter)
    .attr('data-d', d => d)
    .call(component);

  update.exit()
    .remove();
};

const render = () => {
  d3.select('body')
    .datum(root)
    .call(component);
};

render();
```

The first render everything is ok because the selectAll finds nothing and so all nodes are added as expected. The second call to render is where it falls apart because the selectAll finds not just the children but all of the descendant nodes. It's an easy fix once you know what's going wrong -
```js
const parentNodes = selection.nodes();

const update = selection.selectAll('p')
  .filter((d, i, nodes) => parentNodes.indexOf(nodes[i].parentNode) > -1)
  .data(d => d);
```

The original code snippet was a work in progress towards this example. 

Now, I was going to leave things there but I suppose, whilst I'm chatting to the expert I may as well ask: after the second render without the filtering, things don't quite look the way I'd expect them to ([codepen](https://codepen.io/anon/pen/EyQdbJ?editors=1111))-

```html
<p data-d="1,2,3">
  <p data-d="1"></p>
  <p data-d="2"></p>
</p>
```

I can explain why there's only 1 top-level `p` (it's selecting all descendants matching `p`, then removing those for which it has no data item i.e. i > 2) but not why there are only 2 second-level `p` elements (there should be 3).

**Comment by mbostock** [comment]
It’s a combination of *selection*.selectAll matching all descendants, and the fact that you exit.remove AFTER recursively calling your component.

**Comment by mbostock** [comment]
Also, I would use a custom selector that only matches direct children if you want to do something like this. The simplest would be:

```js
selection
  .selectAll(function() { return this.children; })
  .filter("p");
```

**Comment by chrisprice** [comment]
Just realised I didn't say thank you for this. Thanks! That was exactly what was happening and the snippet does indeed simplify things.
