### ISSUE TITLE
Confusion with new selection.merge method

### ISSUE THREAD

**Issue by lazarillo** [d3/d3-selection#86]
Within the documentation, in the selection.merge method, is the following snippet:

-----

This method is commonly used to merge the enter and update selections after a data-join. After modifying the entering and updating elements separately, you can merge the two selections and perform operations on both without duplicate code. For example:

    var circle = svg.selectAll("circle").data(data) // UPDATE
        .style("fill", "blue");

    circle.exit().remove(); // EXIT

    circle.enter().append("circle") // ENTER
        .style("fill", "green")
      .merge(circle) // ENTER + UPDATE
        .style("stroke", "black");

This method is not intended for concatenating arbitrary selections, however: if both this selection and the specified other selection have (non-null) elements at the same index, this selection’s element is returned in the merge and the other selection’s element is ignored.

-----

I am more confused with how merge functions than how the previous EXIT / ENTER / UPDATE paradigm worked in V3.

I am unclear as to what the *passed selection parameter* represents.  In this example here, and in the [What Makes Good Software?](https://medium.com/@mbostock/what-makes-software-good-943557f8a488#.h3nxle4a4) example, the selection parameter is simply the object itself.  I am talking about **`circle`** in the code above `.merge(`**`circle`**`) // ENTER + UPDATE`.

Yes, `circle` is the selection of joined data & SVG circle objects.  And yes, in some way I recognize that the array size of the method parameter `circle` is necessarily different from that of the `circle` used in the **`circle`**`.enter().append("circle")`.  I am *presuming* the difference between those two `circle` variables is that the one associated with the `.enter().append` includes new DOM / SVG circle elements, whereas the one that is passed as a parameter does not.

However, I am really *guessing* in my assumptions because that seems to make the most sense.  Can an example be added that clearly explained what is really happening, and what that **parameter** `circle` is?  Specifically, I'd like some clarification in the following two ways:

 1. Can some further text explain what the code do?  E.g., something like, "current circles will be filled with blue, then old circles - those without any associated data - will be removed, then new circles will be added and colored green, then **???**"  I am presuming the ??? will be something like "older circles with associated data will be colored black".  But maybe it's "all circles with associated data will be colored black".  I really don't know.

 2. Can we have an example that is more useful?  If I understand the code snippet, there are changes made to the circles that are so transitory as to be invisible.  If we want to see the changes, can we make the above code snippet more like [this beautifully clear demonstration](https://bl.ocks.org/mbostock/3808234)?

Thanks!

**Comment by mbostock** [comment]
I will try to give a longer answer later (when I am not on my phone), but quickly: `circle` always refers to exactly the same thing because selections are immutable in D3 4.0+. The `circle` selection returned by *selection*.data represents the UPDATE selection. Later *selection*.merge is used to create a new selection which represents the union of this UPDATE selection with the “materialized” ENTER selection (the result of `circle.enter().append(…)`.

**Comment by mbostock** [comment]
My take is that you were looking for a more complete explanation of the data-join and the general update pattern. The appropriate place for that is in [*selection*.data](https://github.com/d3/d3-selection#selection_data), not [*selection*.merge](https://github.com/d3/d3-selection#selection_merge), so I’ve added a link from the example in *selection*.merge to a new example in *selection*.data that explains the steps in the general update pattern in more detail.

**Comment by lazarillo** [comment]
Thank you very much, Mike!  The link to *`selection`*`.data` from the *`selection`*`.merge` is good, and the very clear break down within the *`selection`*`.data` is excellent!

I still have some questions remaining, if you don't mind:

 - > In item (7) of the `selection.data` example, you have "`.merge(circle) // 7`:  A new selection representing the union of entering and updating circles is created."  I still don't understand why passing the `circle` object as a parameter is necessary or useful, since I cannot think of a case where any other object would or could successfully be passed.

 - > You mentioned that in V4 selections are immutable.  But doesn't `circle` represent a selection that is being altered, whereby DOM objects are dropped from it, data is added / updated to it, and DOM objects are added?

Thanks so much for your time!  I love D3, just trying to wrap my head around these issues.

**Comment by mbostock** [comment]
For the first point, I agree it’s not especially useful (currently) to pass the *other* selection to *selection*.merge, since the vast majority of that time it will be the update selection.

Partly this is a holdover from when *selection*.filter preserved the index of the original *selection* in the filtered selection, so you could use *selection*.merge to union filtered selection; that’s still possible using *selection*.select with a selector function that returns null, but it’s not very common. It would be nice to make *selection*.merge a little more flexible in how it unions selections (related d3/d3#399), but there are some subtleties here about how you handle null elements, and whether the returned selection preserves the indexes of the current *selection*, the *other* selection, or neither. I opted for the simplest implementation at the moment to handle unioning ENTER + UPDATE, but I could see making it more flexible in the future with more thought.

The other reason that *selection*.merge takes a selection is that there’s no reference from the materialized ENTER selection back to the UPDATE selection (nor *vice versa*), so you’d need to propagate that reference somehow. That’s doable, surely, but it does feel a little more complicated.

For the second, selections are immutable so the `circle` definition never changes. However, the DOM is necessarily mutable, so the selected elements can be added or removed to the DOM or have their contents changed. The mutability / immutability refers to membership in the selection, not each element itself. So when you *selection*.append, you’re creating a new selection and you’re creating new elements and you’re adding them to the DOM, but the number of elements and the references to the elements in that *selection* never change, even if you subsequently *selection*.remove; it just means those elements are now detached from the DOM.

**Comment by lazarillo** [comment]
Awesome, thanks!!  I have to say, it's so cool to be able to dialog with "the guy" about things I don't get.  :)

**Comment by devarajan00** [comment]
is selection.merge available in d3.v3.js

**Comment by mp4man** [comment]
How can one update the data for a child – e.g. a "title" tooltip (see eg http://bl.ocks.org/ilyabo/1339996) – with the new (v4) approach?

I have the code below (which appears to work). I would like to use selection.merge
and share the UPDATE code. However, I don't see how to add the "title" nodes only for enter() and use selection.merge.

let theSectorMap =
   d3.select("g#zoom")
	.selectAll("path.feature")
	.data(fm.features)
			       
//UPDATE
theSectorMap
   .attr("d", path)
   .select("title")
   .text(d=>d.properties.name)

theSectorMap.exit()
   .remove()

//ENTER
theSectorMap
   .enter().append("path")
   .attr("class", "feature")
   .on("click", clicked)
   .attr("d", path)
   .append("title")
   .text(d=>d.properties.name)

**Comment by mbostock** [comment]
Mostly the problem is that you are trying to do everything with a single method chain. It becomes easier if you break it out into separate chains:

```js
let feature = d3.select("#zoom")
  .selectAll(".feature")
  .data(fm.features);

feature.exit().remove();

let featureEnter = feature.enter().append("path")
    .attr("class", "feature")
    .on("click", clicked);

featureEnter.append("title");

feature.merge(featureEnter)
    .attr("d", path)
  .select("title")
    .text(d=>d.properties.name);
```

Or, a slight variation that is more efficient since you avoid re-selecting the entering titles:

```js
let feature = d3.select("#zoom")
  .selectAll(".feature")
  .data(fm.features);

feature.exit().remove();

let title = feature.select("title");

let featureEnter = feature.enter().append("path")
    .attr("class", "feature")
    .on("click", clicked);

let titleEnter = featureEnter.append("title");

feature.merge(featureEnter)
    .attr("d", path);

title.merge(titleEnter)
    .text(d=>d.properties.name);
```

Even better, you should consider using a key function on your data-join, probably `d => d.properties.name`, so that you don’t have to update the title text after your data-join since any updating element will be rebound to the existing element. (If you have duplicate names, the duplicates will be entered & exited rather than updated, but that’s probably fine.) Even better if this means you also don’t have to update the d attribute!

```js
let feature = d3.select("#zoom")
  .selectAll(".feature")
  .data(fm.features, d => d.properties.name);

feature.exit().remove();

let featureEnter = feature.enter().append("path")
    .attr("class", "feature")
    .on("click", clicked);

featureEnter.append("title")
    .text(d=>d.properties.name);

feature.merge(featureEnter)
    .attr("d", path);
```

Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by cool-Blue** [comment]
Can I suggest a slight change to the docs (I don't think it warrants a PR)?
```js
var circle = svg.selectAll("circle").data(data) // UPDATE
    .style("fill", "blue");

circle.exit().remove(); // EXIT

circle.enter().append("circle") // ENTER; modifies UPDATE! 🌶
    .style("fill", "green");

circle // ENTER + UPDATE
    .style("stroke", "black");

circle.call(foo)
```
Would be rewritten in 4.0 as:
```js
var circle = svg.selectAll("circle").data(data) // UPDATE
    .style("fill", "blue");

circle.exit().remove(); // EXIT

circle = circle.enter().append("circle") // ENTER - added "circle = "
    .style("fill", "green")
  .merge(circle) // ENTER + UPDATE
    .style("stroke", "black");

// OR
circle = circle.merge(circle.enter().append("circle").style("fill", "green"))
  .style("stroke", "black");

circle.call(foo)  // same result as before
```

The current explanation is confusing if you are porting from V3, because V3 delivers a reference to a fully updated selection that reflects the subsequent, data-driven DOM state, which is often what you want.

I was actually less confused with the old way but sure: side effects are bad mmkay.

**Comment by curran** [comment]
@cool-Blue A PR would be helpful if you'd like to add these changes.

It took some time to realize that by "the docs", you're referring to this file https://github.com/d3/d3/blob/master/CHANGES.md#selections-d3-selection 

Some notes on the content (which would be great to discuss in a PR):

 * The code that comes after `// OR` should probably be its own separate block. On first reading, I thought "Why is circle being reassigned twice, the second time merging the merged selection another merged selection?"
* If this were included, the definition of `foo` should probably also be included. As it is here, the reader must speculate as to how `foo` might be defined, which would probably be a source of frustration.

**Comment by computed** [comment]
I am using the merge parameter when my chain selection has traveled down the DOM hierarchy to sub-tag elements, like this:

.merge(selection.selectAll("circle")).attr("cx",function(d){...})... and so on

seems to work OK.
so I would not like the parameter to disappear.
