### ISSUE TITLE
Idea: selectAppend

### ISSUE THREAD

**Issue by aubergene** [d3/d3-selection#91]
I often want to create a function that can be repeatedly called to render the current state of an object. Due to the nature of HTML/SVG I need to add a wrapper element around a collection of inner elements, at present I don't feel there is a good standard way to do this in D3.

In a lot of the examples such wrapper elements are created prior to data binding, but I feel this doesn't work well with larger projects or when trying to create [reusable charts](https://bost.ocks.org/mike/chart/). 

I've seen various workarounds, such as using `selectAll('ul')` with `.data([null])` but this feels like a hack and it destroys the parent data. 

As I thought about this more, I wondered how often it is useful to call `select` and it to return an empty selection. Perhaps it could be modified so that `select('ul', true)` would create the element if it doesn't exist?

```js
selection.prototype.selectAppend = function(name) {
    var t
    return (t = this.select(name), t.size()) ? t : this.append(name)
}

function render(data) {
    var table = d3.select('body')
        .selectAppend('ul')
        
        .selectAll('li')
        .data(data) // etc

    var table = d3.select('body').selectAppend('table')
    var tbody = table.selectAppend('tbody')
    tbody.selectAll('tr')
        .data(data) // etc
}
```

**Comment by mbostock** [comment]
> I've seen various workarounds, such as using selectAll('ul') with .data([null]) but this feels like a hack and it destroys the parent data.

Depending on how it’s done this should not be considered a hack; creating an element if it does not exist can be done using the [general update pattern](https://bl.ocks.org/mbostock/3808218), and the only difference is that the dataset is hard-coded to have a single element rather than being dynamic. And you omit the *exit* part of the general update because you only care about creating the element if it does not exist. This technique is used, for example, in [d3-axis](https://github.com/d3/d3-axis/blob/master/src/axis.js#L50) to create the domain path element if it does not already exist.

The primary advantage of the general update pattern (and the data join more generally) is that you can control what gets run separately on *enter*, *update* and *exit*. So you can avoid running redundant code on *update* if your element already exists. For example, the axis doesn’t need to set the class and stroke attributes on the domain path if that element already exists, because those attributes are constant and were set when the element was previously created.

If you instead have a *selection*.selectAppend-type method, it encourages you to run the same code on both *enter* and *update*, even when running that code on *update* is unnecessary. Also there’s the principle of parsimony, which says that since D3 already provides a satisfactory way to create an element if it doesn’t exist, we should avoid introducing a competing way of doing it. (Competing methods make usage less consistent and impede learning.)

You don’t need to use `[null]` as the single-element dataset, of course. If you want to propagate the data from the parent, could do something like this:

```js
var child = parent.selectAll("child")
  .data(function(d) { return [d]; });

// Create the only child if it does not yet exist.
// When creating the only child, set its class to "only-child".
child = child.enter().append("child")
    .attr("class", "only-child")
  .merge(child);

// Update the only child’s name attribute using the new data.
// This applies to both enter and update.
child.attr("name", function(d) { return d.name; });
```

My primary objection to this pattern is that it’s not possible to chain the creation of the only-child, mostly because you have to reassign `child = …` after [merging](https://github.com/d3/d3-selection/blob/master/README.md#selection_merge) enter and update. It’d be nice to have something more succinct but functionally-equivalent, say like this:

```js
var child = parent.selectAll("child")
  .data(function(d) { return [d]; })
  .enter().append("child")
    .attr("class", "only-child")
  .update() // merges ENTER’d child with UPDATE
    .attr("name", function(d) { return d.name; });
```

I dunno whether *selection*.update is the right name for that method; that might be confusing since it’s merging the materialized *enter* selection with the *update* selection. You could use a longer name like *selection*.enterUpdate, or you could use the existing *selection*.merge method and default to the associated *update* selection if no *other* selection is passed. Related #89 #86 d3/d3#399.

It’s also fair to argue that this code is too long…

```js
var child = parent.selectAll("child")
  .data(function(d) { return [d]; })
  .enter().append("child")
  .update()
    .attr("name", function(d) { return d.name; });
```

And it’d be better to have a shorthand syntax for it…

```js
var child = parent.selectAppend("child")
    .attr("name", function(d) { return d.name; });
```

But as I said already, this violates parsimony and doesn’t generalize well, so I’m inclined against it. Though see d3-jetpack and d3-starterkit for some D3 extensions that offer more convenience methods. And see #79 for a discussion on *selection*.selectNone and *selection*.selectData for a more general convenience function related to the data-join.

A different approach to this problem, closer to your original suggestion, is to pass *selection*.select a function like this:

```js
var table = d3.select("body").select(function() {
  return this.querySelector("table") || this.ownerDocument.createElement("table");
});
```

**Comment by aubergene** [comment]
Thanks, that was helpful! I got Adam to merge something along these lines into [d3-jetpack-module](https://github.com/1wheel/d3-jetpack-module/commit/2c55624e7a01a32307b217af6c312eb93143d757), which is handy as it also uses the jetpack `append` so it will take care of setting id and classes at append time too, and usually that's all that's needed for wrapper tags and suchlike.

**Comment by mbostock** [comment]
Cool. I’d consider doing something on a per-element basis than a per-selection basis, though, like so (not tested):

```js
d3.selection.prototype.selectAppend = function(name) {
  var select = d3.selector(name),
      create = d3.creator(name);
  return this.select(function() {
    return select.apply(this, arguments)
        || create.apply(this, arguments);  
  });
};
```

That way if you run *selection*.selectAppend on a selection with multiple elements, it will do the right thing for each element, rather than checking the total *selection*.size.

**Comment by curran** [comment]
Here's what the pattern looks like with the new `.join` syntax, for example to select or append a single `<g>` element:

```js
selection.selectAll('g').data([null]).join('g').attr( ... );
```

**Comment by curran** [comment]
That said, it is rather tantalizing to consider a shorthand API for this very common special case, such as:

```js
selection.one('g').attr( ... );
```
