### ISSUE TITLE
Idea: *selection*.end()

### ISSUE THREAD

**Issue by au-phiware** [d3/d3-selection#98]
I'm a fan of jQuery's [`.end()`](http://api.jquery.com/end/) method. I think a similar `d3-selection` method would be useful.

Example:

    d3.select('body')
      .selectAll('svg')
        .data(...)
        .enter()
          .append('svg')
            .attr(...)
            .append('g')
              .each(...)
            .end() // g
          .end() // svg
          .append('p').text("I'm below each svg element.").end()
        .end() // enter
      .end() // join
      .append('p').text("I'm at the end of the body element.");

Not sure how it would work with `merge`, or if the data join causes other problems.

Would you be interested if I wrote a quick PR?

**Comment by mbostock** [comment]
This is a little different but related to ideas discussed previously in d3/d3#1966 and [d3/d3#1618](https://github.com/d3/d3/pull/1618#issuecomment-28078881). This is different in that it explicit refers to the originating selection rather than being a DOM-based operation (so each selection would need to track its originating selection to move back up the method chaining stack). My recommendation is that you use a local variable rather than trying to do everything as a single statement with method chaining, but I suspect that with some effort you could implement such a feature with a plugin that extends the d3.selection.prototype.

**Comment by 1wheel** [comment]
I think you could use the [d3.parent](https://github.com/vijithassar/d3-parent) plugin to do this.

**Comment by au-phiware** [comment]
Thanks for the feedback.

I agree that I am attempting to achieve a similar coding style as in d3/d3#1966. But, as already noted, it is less about navigating the DOM and more about returning to a previous state (i.e. the originating selection). The [d3.parent][1] plugin is solving a different problem and would work in many cases but wouldn't help when using `filter` and data joins.

To implement my idea as a plugin would require wrapping (almost) every method that produces a new Selection and associating the originating selection to the new selection, effectively building a stack of selections. The alternative would be to maintain a heap of stacks and wrap the constructor and somehow determine which stack to push it on to (I don't think that information would be available to the constructor). The former approach is very sensitive to changes to the d3-selection module; whenever a new selection is returned from a future method it would need to be wrapped by the plugin. The effort of maintenance doesn't seem to be worth, what is essentially, a stylistic preference of my own. I might change my mind and put the effort in but for now I'll close this issue :)

[1]: https://github.com/vijithassar/d3-parent

**Comment by mbostock** [comment]
It’s true, but some methods such as *selection*.append and *selection*.insert are built on top of *selection*.select, so it might not be a small enough set of methods to be feasible. And I don’t currently anticipate new methods that construct selections directly… but anything is possible.
